const allBranches = [
    {value: "Efectimundo_Atizapan_Plaza_Cristal", label: "Atizapán Plaza Cristal"},
    {value: "Efectimundo_Azcapotzalco", label: "Azcapotzalco"},
    {value: "Efectimundo_Cancun_MultiPlaza_Arco_Norte", label: "Cancún Arco Norte"},
    {value: "Efectimundo_Chalco_Centro", label: "Chalco Centro"},
    {value: "Efectimundo_Chalco_Guadalupana", label: "Chalco Guadalupana"},
    {value: "Efectimundo_Chalco_Soriana_Valle", label: "Chalco Soriana Valle"},
    {value: "Efectimundo_Chilpancingo", label: "Chilpancingo"},
    {value: "Efectimundo_Chimalhuacan_Barrio_Artesanos", label: "Chimalhuacán Artesanos"},
    {value: "Efectimundo_Chimalhuacan_Centro", label: "Chimalhuacán Centro"},
    {value: "Efectimundo_Chimalhuacan_Las_Torres", label: "Chimalhuacán Las Torres"},
    {value: "Efectimundo_Coacalco_Bosques_del_Valle", label: "Coacalco Bosques"},
    {value: "Efectimundo_Coacalco_Power_Center", label: "Coacalco Power Center"},
    {value: "Efectimundo_Coyoacan_Plaza_Cantil", label: "Coyoacán Plaza Cantil"},
    {value: "Efectimundo_Cuajimalpa", label: "Cuajimalpa"},
    {value: "Efectimundo_Cuautepec", label: "Cuautepec"},
    {value: "Efectimundo_Cuautepec_Barrio_Alto", label: "Cuautepec Barrio Alto"},
    {value: "Efectimundo_Cuautitlan_Izcalli_Portal_Cuautitlan", label: "Izcalli Portal"},
    {value: "Efectimundo_Cuautla_Morelos", label: "Cuautla Morelos"},
    {value: "Efectimundo_Durango", label: "Durango"},
    {value: "Efectimundo_Ecatepec_Plaza_Ecatepec", label: "Ecatepec Plaza"},
    {value: "Efectimundo_Guadalajara_Plaza_Del_Sol", label: "Guadalajara Plaza del Sol"},
    {value: "Efectimundo_Guadalajara_Plaza_Mich", label: "Guadalajara Plaza Mich"},
    {value: "Efectimundo_Iztapaluca", label: "Iztapaluca"},
    {value: "Efectimundo_La_Paz_Estado_De_Mexico", label: "La Paz"},
    {value: "Efectimundo_Leon_Central", label: "León Central"},
    {value: "Efectimundo_Leon_Plaza_Mayor", label: "León Plaza Mayor"},
    {value: "Efectimundo_Lerma", label: "Lerma"},
    {value: "Efectimundo_Merida_Plaza_Las_Americas", label: "Mérida Plaza Las Américas"},
    {value: "Efectimundo_Merida_Plaza_Thread", label: "Mérida Plaza Thread"},
    {value: "Efectimundo_Metepec_Plaza_News", label: "Metepec Plaza News"},
    {value: "Efectimundo_Mexico_Plaza_Loreto", label: "Plaza Loreto"},
    {value: "Efectimundo_Mexico_Plaza_San_Angel", label: "Plaza San Ángel"},
    {value: "Efectimundo_Monterrey_Facp", label: "Monterrey FAcP"},
    {value: "Efectimundo_Monterrey_Plaza_Ciclon", label: "Monterrey Plaza Ciclón"},
    {value: "Efectimundo_Naucalpan_Plaza_Naucalpan", label: "Naucalpan Plaza"},
    {value: "Efectimundo_Nezahualcóyotl_Central", label: "Nezahualcóyotl Central"},
    {value: "Efectimundo_Nezahualcóyotl_Plaza_Aragon", label: "Nezahualcóyotl Aragón"},
    {value: "Efectimundo_Pachuca", label: "Pachuca"},
    {value: "Efectimundo_Plaza_Boulevard", label: "Plaza Boulevard"},
    {value: "Efectimundo_Plaza_Cantiles", label: "Plaza Cantiles"},
    {value: "Efectimundo_Plaza_Central", label: "Plaza Central"},
    {value: "Efectimundo_Plaza_La_Cumbre", label: "Plaza La Cumbre"},
    {value: "Efectimundo_Plaza_Las_Hadas", label: "Plaza Las Hadas"},
    {value: "Efectimundo_Puebla_Plaza_Dorada", label: "Puebla Plaza Dorada"},
    {value: "Efectimundo_Puebla_Plaza_San_Angel", label: "Puebla San Ángel"},
    {value: "Efectimundo_Queretaro_Plaza_Anfor", label: "Querétaro Plaza Anfor"},
    {value: "Efectimundo_Queretaro_Plaza_Zaragoza", label: "Querétaro Plaza Zaragoza"},
    {value: "Efectimundo_San_Juan_del_Rio", label: "San Juan del Río"},
    {value: "Efectimundo_San_Luis_Potosi_El_Doral", label: "San Luis Potosí El Doral"},
    {value: "Efectimundo_San_Luis_Potosi_Plaza_Cactus", label: "San Luis Potosí Cactus"},
    {value: "Efectimundo_Tepic", label: "Tepic"},
    {value: "Efectimundo_Tijuana_Av_Principal", label: "Tijuana Av Principal"},
    {value: "Efectimundo_Tijuana_Plaza_Fidelidad", label: "Tijuana Plaza Fidelidad"},
    {value: "Efectimundo_Tlalnepantla_Plaza_Tlalnepantla", label: "Tlalnepantla Plaza"},
    {value: "Efectimundo_Toluca_Plaza_Digital", label: "Toluca Plaza Digital"},
    {value: "Efectimundo_Torreon_Paseo_La_Roma", label: "Torreón Paseo La Roma"},
    {value: "Efectimundo_Tuxtla_Gutierrez", label: "Tuxtla Gutiérrez"},
    {value: "Efectimundo_Veracruz_Plaza_Veracruz", label: "Veracruz Plaza"},
    {value: "Efectimundo_Villahermosa_Atrio", label: "Villahermosa Atrio"},
    {value: "Efectimundo_Zacatecas", label: "Zacatecas"}
];